
#- name: Remove directories for node_exporter
#  file:
#    path: "{{ item }}"
#    state: absent
#  loop:
#    - '/usr/local/bin/node_exporter'


- name: Create User nodeuser
  user:
    name: nodeuser
    create_home: no
    shell: /bin/false

- name: Create directories for node_exporter
  file:
    path: "{{ item }}"
    state: directory
    owner: nodeuser
    group: nodeuser
  loop:
    - '/tmp/node_exporter'

- name: Download And Unzipped node_exporter
  unarchive:    
    src: https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz
    dest: /tmp/node_exporter
    creates: /tmp/node_exporter/node_exporter-{{ node_exporter_version }}.linux-amd64
    remote_src: yes

- name: Copy Bin Files From Unzipped to node_exporter
  copy:
    src: /tmp/node_exporter/node_exporter-{{ node_exporter_version }}.linux-amd64/{{ item }}
    dest: /usr/local/bin/
    remote_src: yes
    mode: preserve
    owner: nodeuser
    group: nodeuser
  loop: [ 'node_exporter' ]

- name: Create File for node_exporter Systemd
  template:
    src=templates/node_exporter.service
    dest=/etc/systemd/system/
  notify:
    - systemd reload

- name: Systemctl node_exporter Start
  systemd:
    name: node_exporter
    state: started
    enabled: yes



