all:
  hosts:
    mon1:
      ansible_host: 146.185.208.233
    db01:
      ansible_host: 87.239.110.163
    db02:
      ansible_host: 95.163.181.240
    db03:
      ansible_host: 89.208.208.226
    app1:
      ansible_host: 89.208.229.210
    app2:
      ansible_host: 87.239.106.96

  children:
    dbservers:
      hosts:
        db0[1:3]:

    appservers:
      hosts:
        app[1:2]:

    monservers:
      hosts:
        mon1:
