---

- hosts: monitoring
  become: true
  vars_files:
     - vars/passwords.yaml
  roles:
     - prometheus
  tags: prometheus,monitoring

- hosts: monitoring
  become: true
  vars_files:
     - vars/passwords.yaml
  roles:
     - grafana
  tags: grafana,monitoring

- hosts: all
  become: true
  vars_files:
     - vars/passwords.yaml
  roles:
     - node_exporter
  tags: node_exporter,monitoring

- hosts: all
  become: true
  vars_files:
     - vars/passwords.yaml
  roles: 
     - install_server
  tags: install_server

#- hosts: app2
#  become: yes
#  roles:
